sudo: required
dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script: pytest
after_script: cd ~
deploy:
  provider: pypi
  user: arnavkohli
deployment:
  password:
    secure: VjvFlXsi0YhzHsg3VXrjrxbvCoC3r14VHH/ZxikVjlbwk8/sbcsZjGUIXwo0wFoWAkmv7aTlXM9fGjGZfgLG2fA+1wZ0LrfUJkdcsbUP5lBdlEfrCRlPabBNaOaB0zOzw0OdJUeFvRb4r5T9ttzEdX3W0BdQUMLsRzaWZOa5xSrs4E8E1mjtdVIRS8puyZrWdcuG4Mz9Cy/1N2VKa1z/oNVBs+qWsNmsVhxyGMnU/vUe1aw0WZf1gGNJsFGG2PkEST7q+F1my19x3nK0IQvi/IFGHTzsPzphrjRmTmnkKkxS5dofwljJQ//iJEM7ckBNLkaWG8ShUZ7DJlbrlmW7PQHklDLd1d39aqFc0qMXWb4yZ/u2vPuNh83kZ0N/9q9z/n684qn45Zh0da6PzvN9ypML/PQG5gNFb4nMD/vz6xA8QCA+o3fsd888CpLkahaTE6u9ZhiIr4qFvZFqhzzm5aibdwiuZYOVS27Gf4dVDqVDQoM7t0GjL+9A707/ZVvrfcgvxzA46T2gUhRaN4Yu8FAWdrxw0VrFGRPbloIjVNtyRbu3HYT15CmXyqJ9QPMbMJ5dgtLjpBU/uqvRW2ODsWPs8zhfx0vVsIDoLcfaTCKb0GBs19zAhoHX03+puhct3EjGE6JeKewPGCipuix13zmYnrQLKlfQd740NDHRyuI=
