sudo: required
dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script: pytest
after_script: cd ~
deploy:
  provider: pypi
  user: arnavkohli
  password:
    secure: PCwuG/r4zT9VCKGGFK4NSzxTL/U5XgBiALMA102qVZlEsuhXCXbxzcG7htpyvSt+kADWQ10aaa9xSUYGGtEMddYrmo9peFOMcnHiG5wOQVIoX08rTkb0kcSl0saxZmb23G3SDUPZRs7+h7giiV+rE+U2IwTRN2Y7rIQxOqMqGbS5lTcDCNkOtiBGyNWe/xXrrQNaPXjiV1RNZp1IhnsiBXE+fZVMdKCFTmn/L5QCj9m7pkNJ+IMSIlFzx7xiCt3p8Gug3PKbWDBy1wBzJ1DZBmtVXX6vPR/Ya9oQA5px7QrxDjPcIssnZToT13c9BmVR7H194tqJZ9H1GqFo5bKtihgBPU8idpAufRny6aDKm577cg1BRvysSZZdl/POvvH3RMMYExYDq2sfdT26gko6bmpgX1317oleibQ8CfvnUt0Avj+DWCcCOiqthHQuFqLjK6ebabSDMs7xN85mbEbWsSW6AtKcOO/ZH8ppI5f9T7hJZGKjc1tcjoZFtc1NV4yhwx6GuDY/zwSdEQrSSsDVIlAIAg2krGcmxveUwwWzmdGmMs2q028bc84DBGBmPaLi2FC743Y9b/yO2bvqnJpUecmy6yQC4bY4pRfJyYbKSOKsk9ZSdW5PxC5jCF4JH1LE/ewkhNs0BZqIzhYzpA+XwpNQLBJbljTJkmGz4CiK5Q4=
