sudo: required
dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script: pytest
after_script: cd ~
deploy:
  provider: pypi
  user: arnavkohli
deployment:
  password:
    secure: U8dmST8cD5+w1h6G4d691826PK5hZejb1oOoTVFe4fFhsFgyZP2M3ug4qs/YMllOBoEu4hPYhkBJpH6f971eTlU5HRF/vhqlrTRxwZNV+5rzG1S0zQw4Eu5M1/WPt412iy7JPVv8ra+vWWQXgKZulRbmRwrc+NFf9DOqrdeSLbX34YNLrfKzobJSP6wzJTk9MBQ95n8N94ixtSWJffqFIHLVADwMemmO3bxWIkE+S4sfk3hvfWgBVl+PZ1SddOs/64gTJAl8XDkcRUXm/DoFtkJ0cMdvLNXMHZcUHI+wcGd0bk9E3DnjaZ8dcW4fLwGBoGdqZ95vt1/uJ+LdfdbIN7egB5tPr6WS7/zQuGWfYOZO+2zZYN9YLjJK87CDzR/iEJsCFS2W/joiwN1AKcflEe1kWmD2tNnELfPPoATut+T+GVLW3CjcEqK2XFAWInoOj1cohpCZ07s1585CWzu375xOODubJ44Qti0vy9WsEAKDNLrjcE8qXVObr3OyoIbqls47l3bC1bhnNob1IPfquuoUbg7rqz1MJz33v2j2Mbh3l7CXc6CnL43sSnh4twwQYWPoAeN/EsZJJHOAyswoDG59tfEmfyYC4Z0J9BumhBwi0iIYlbcKKTSCM9BztQh/VnRfhdzB5sDu7M2ECFycWx0c1MAN1qPSjgPr5x+5b4g=
